insert into PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_ECONOMATO) values (1, 'CHOCOLATE', 2.1, 73, 1);
insert into PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_ECONOMATO) values (2, 'TABACO', 7.09, 100, 1);
insert into PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_ECONOMATO) values (3, 'GEL', 1.48, 86, 1);
insert into PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_ECONOMATO) values (4, 'CAFE', 0.6, 38, 1);
insert into PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_ECONOMATO) values (5, 'PATATAS FRITAS', 8.32, 57, 1);
