create or replace TRIGGER REGISTRO_AUDIT_<<NOMBRE_TABLA>>
AFTER DELETE OR INSERT OR UPDATE ON <<NOMBRE_TABLA>>
declare table_name varchar(30) := '<<NOMBRE_TABLA>>';
BEGIN
  IF INSERTING THEN
    INSERT INTO AUDIT_TABLE (USUARIO,TIPO,TABLA) VALUES (USER,'INSERT', table_name);
    
  ELSIF DELETING THEN
    INSERT INTO AUDIT_TABLE (USUARIO,TIPO,TABLA) VALUES (USER,'DELETE', table_name);
    
  ELSIF UPDATING THEN
    INSERT INTO AUDIT_TABLE (USUARIO,TIPO,TABLA) VALUES (USER,'UPDATE',  table_name);
  END IF;
END;