insert into MODULO (ID_MODULO, CARCEL_COD_CARCEL, TIPO_MODULO) values (1, 98212558, CALABOZO);
insert into MODULO (ID_MODULO, CARCEL_COD_CARCEL, TIPO_MODULO) values (2, 98212558, STANDARD);
insert into MODULO (ID_MODULO, CARCEL_COD_CARCEL, TIPO_MODULO) values (3, 98212558, MAX_SEGURIDAD);
