insert into PRODUCTO (ID_PRODUCTO, PRECIO, NOMBRE, STOCK, ID_ECONOMATO) values (1, 2.1, 'CHOCOLATE', 73, 1);
insert into PRODUCTO (ID_PRODUCTO, PRECIO, NOMBRE, STOCK, ID_ECONOMATO) values (2, 7.09, 'TABACO', 100, 1);
insert into PRODUCTO (ID_PRODUCTO, PRECIO, NOMBRE, STOCK, ID_ECONOMATO) values (3, 1.48, 'GEL', 86, 1);
insert into PRODUCTO (ID_PRODUCTO, PRECIO, NOMBRE, STOCK, ID_ECONOMATO) values (4, 0.6, 'CAFE', 38, 1);
insert into PRODUCTO (ID_PRODUCTO, PRECIO, NOMBRE, STOCK, ID_ECONOMATO) values (5, 8.32, 'PATATAS FRITAS', 57, 1);
