insert into ZONA_ACTIVIDADES (ID_ZONA, COD_CARCEL, AFORO_MAX, TIPO) values (1, 98212558, 5, 'VISITAS');
insert into ZONA_ACTIVIDADES (ID_ZONA, COD_CARCEL, AFORO_MAX, TIPO) values (2, 98212558, 10, 'GIMNASIO');
insert into ZONA_ACTIVIDADES (ID_ZONA, COD_CARCEL, AFORO_MAX, TIPO) values (3, 98212558, 5, 'BIBLIOTECA');
